name: Run Python Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python main.py # Replace 'main.py' with your entry script

      - name: Run script 2
        run: |
          python TimCode.py # Replace 'main.py' with your entry script
